# 0. Visualition of Pilot Site Locations ---------------------------------------

# This script outputs a .svg map of the UK saved in your current working
# directory that highlights the top 10 PCNs that are under referring instances
# of suspected skin cancer according to the model generated by
# referral_prediction_model.R.

# 1. Load packages -------------------------------------------------------------
library(tidyverse)
library(maps)


# 2. Create approximate PCN location lookup ------------------------------------
# These locations are approximated. Note that if you run the model again it is
# likely that the PCNs selected will be different and you will need to create
# new coordinates for those PCNs.

pcn_locations <- tribble(
  ~PCNCode, ~latitude, ~longitude,
  "U16464", 53.5526, -1.4797, # Barnsley
  "U20871", 50.7950, -1.1290, # Gosport Central
  "U62384", 53.7676, -0.3274, # Hull Modality Partnership
  "U63565", 51.9923, -2.1579, # TWNS
  "U20639", 51.7130, -0.4500, # Delta
  "U16338", 51.8780, -2.1700, # North and South Gloucester
  "U19031", 52.3024, -0.6937, # Wellingborough and District
  "U09772", 52.3976, -0.7290, # Red Kite Healthcare
  "U67032", 51.3370, -0.7420, # Surrey Heath
  "U03824", 53.7676, -0.3274  # Venn
)


# 3. Select the top 10 potential pilot sites -----------------------------------

pilot_top10 <- pilot_sites |>
  slice_max(
    estimated_referral_gap,
    n = 10,
    with_ties = FALSE
  ) |>
  left_join(
    pcn_locations,
    by = "PCNCode"
  ) |>
  mutate(
    # Slightly separate the two Hull PCNs for presentation
    plot_longitude = case_when(
      PCNCode == "U62384" ~ longitude - 0.10,
      PCNCode == "U03824" ~ longitude + 0.10,
      TRUE ~ longitude
    ),
    plot_latitude = case_when(
      PCNCode == "U62384" ~ latitude + 0.07,
      PCNCode == "U03824" ~ latitude - 0.07,
      TRUE ~ latitude
    )
  ) |>
  arrange(desc(estimated_referral_gap))


# 4. Prepare the base map ------------------------------------------------------

england_map <- map_data("world") |>
  filter(region == "UK")


# 5. Plot the top 10 potential pilot sites -------------------------------------

pilot_sites_map <- ggplot() +
  geom_polygon(
    data = england_map,
    aes(
      x = long,
      y = lat,
      group = group
    ),
    fill = "#DCEFF4",
    colour = "white",
    linewidth = 0.4
  ) +
  geom_point(
    data = pilot_top10,
    aes(
      x = plot_longitude,
      y = plot_latitude,
      size = estimated_referral_gap
    ),
    shape = 21,
    fill = "#C9795B",
    colour = "white",
    stroke = 1.2,
    alpha = 0.95
  ) +
  scale_size_continuous(
    range = c(6, 14),
    guide = "none"
  ) +
  coord_quickmap(
    xlim = c(-6.5, 2.2),
    ylim = c(49.8, 56),
    expand = FALSE
  ) +
  theme_void() +
  theme(
    plot.margin = margin(20, 20, 20, 20)
  )

pilot_sites_map


# 7. Save as SVG ---------------------------------------------------------------

ggsave(
  filename = "top_10_pcn_pilot_sites_map.svg",
  plot = pilot_sites_map,
  width = 8,
  height = 9,
  units = "in",
  bg = "white"
)
